config/routes.rb
# -*- encoding : utf-8 -*-
Alfa::Application.routes.draw do

  resources :occupations

  resources :world_readings

  resources :students do
    resources :presence_list_comments
  end

  resources :rooms do
    resources :lecture_days
  end

  root :to => "cores#index"
  resources :cores
  resources :coordinators
  resources :educators
  resources :users
  resources :user_sessions
  match 'sign_up' => 'users#sign_up', :as => 'sign_up'
  match 'sign_in' => 'user_sessions#new', :as => 'sign_in'
  match 'sign_out' => 'user_sessions#destroy', :as => 'sign_out'
  match 'update_city' => 'cores#update_city', :as => 'update_city'
  match 'update_rooms/:educator_id/:core_id' => 'educators#update_rooms', :as => 'update_rooms'
  match 'student_update_rooms/:student_id/:core_id' => 'students#update_rooms', :as => 'student_update_rooms'
  match 'coordinator_update_rooms/:coordinator_id/:core_id' => 'coordinators#update_rooms', :as => 'coordinator_update_rooms'
  match 'students_without_mother_name' => 'students#without_mother_name', :as => 'without_mother_name'
  match 'update_cancelled/:id' => 'lecture_days#update_cancelled', :as => 'update_cancelled'
  match 'new_lecture_day/:room_id' => 'lecture_days#new_lecture_day', :as => 'new_lecture_day'
  match ':room_id/:month/fix_presence_list' => 'presences_list#fix', :as => 'fix_presence_list'
  match ':room_id/:month/finish_presence_list' => 'presences_list#finish', :as => 'finish_presence_list'
  match ':room_id/:month/reopen_presence_list' => 'presences_list#reopen', :as => 'reopen_presence_list'
  match ':room_id/presences_list' => 'presences_list#index', :as => 'presences_list'
  match ':room_id/:month/presences_list' => 'presences_list#edit', :as => 'edit_presences_list'
  match 'update_presence/:id/:status' => 'presences_list#update', :as => 'update_presence'
  match 'update_student_presences/:room_id/:month/:student_id/:status' => 'presences_list#update_student_presences', :as => 'update_student_presences'
  match 'reports' => 'reports#index', :as => 'reports'
  match 'show_report' => 'reports#show', :as => 'show_report'
  match 'report_update_rooms/:core_id' => 'reports#update_rooms', :as => 'report_update_rooms'
  match 'show_full_report' => 'reports#show_full_report', :as => 'show_full_report'

  match 'show_second_report/:column/:second_column/:core_id/:room_id' => 'reports#show_second_report', :as => 'show_second_report'
  match 'students/:student_id/:month/show_presence_list_comments' => 'presence_list_comments#show', :as => 'show_presence_list_comments'
  
end

app/controllers/presences_list_controller.rb
class PresencesListController < ApplicationController
  
  def index
    @room = Room.find(params[:room_id])
    @months = LectureDay.all(:select => "DISTINCT month",:conditions => "room_id = #{params[:room_id]} and month is not null", :order => "year ASC, month ASC").collect(&:month)
  end

  def new
    @presence = Presence.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @presence }
    end
  end

  # GET /presences/1/edit
  def edit
    @presence_list = PresenceList.all(:conditions => "month = #{params[:month]} AND room_id = #{params[:room_id]}", :include => [:student])
    
    @month = params[:month]
    @room = Room.find(params[:room_id])
    @core = @room.core
    @educators = Educator.find_by_sql("
      SELECT e.* FROM educators e INNER JOIN educators_rooms er ON er.educator_id = e.id 
      WHERE er.room_id = #{@room.id}").collect(&:name).join(", ")
    @presences = []
    @students = Student.all(:conditions => "room_id = #{@room.id}", :order => "name ASC")
    @lecture_days = LectureDay.all(:conditions => "room_id = #{params[:room_id]} AND month = #{params[:month]}", :order => "lecture_on ASC")


    if @presence_list.count == 0
      get_presence_list_data
      @type = 0
    else
      @type = 1
      get_data_for_show_presence_list
    end
    
    respond_to do |format|
      format.js
      format.html # index.html.erb
      format.xml  { render :xml => @presences }
    end
  end

  # POST /presences
  # POST /presences.xml
  def create
    @presence = Presence.new(params[:presence])

    respond_to do |format|
      if @presence.save
        format.html { redirect_to(@presence, :notice => 'Presence was successfully created.') }
        format.xml  { render :xml => @presence, :status => :created, :location => @presence }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @presence.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /presences/1
  # PUT /presences/1.xml
  def update
    @presence = Presence.find(params[:id])
    @presence.update_attributes(:presence => params[:status])
    
    respond_to do |format|
      format.js if request.xhr?
    end
  end

  def reopen
    @presence_list = PresenceList.delete_all("month = #{params[:month]} AND room_id = #{params[:room_id]}")
    
    edit
  end

  def finish
    presences = Presence.all(:conditions => "room_id = #{params[:room_id]} AND month = #{params[:month]}", :order => "student_id ASC")
    @room = Room.find(params[:room_id])
    @students = Student.all(:conditions => "room_id = #{@room.id}", :order => "name ASC")
    @presences = []
    i = 0
    @lecture_days = LectureDay.all(:conditions => "room_id = #{params[:room_id]} AND month = #{params[:month]}", :order => "lecture_on ASC")
    @students.each do |s|
      @presences << {} 
      @presences[i][:student] = s.name
      @presences[i][:student_id] = s.id
      @lecture_days.each do |l|
        presences.each do |p|
          @presences[i][l.id] = p if (l.id == p.lecture_day_id && p.student_id == s.id)
        end
      end
      i += 1
    end

    i = 0
    while (i < @students.count) do
      presence_array = []
      total_presence = 0
      total_lectures = 0
      @lecture_days.each do |l|
        p = @presences[i][l.id]
        presence_array << p.id
        total_presence += 1 if p.presence && p.has_class
        total_lectures += 1 if p.has_class
      end
      presence = (total_presence * 100)/total_lectures
      PresenceList.create(:room_id => params[:room_id], :student_id => @students[i].id, :month => params[:month],
        :presences => presence_array.join(","), :presence => presence)
      i += 1
    end
    edit

  end

  def update_student_presences
    @status = params[:status].to_i
    @student = Student.find(params[:student_id])
    ActiveRecord::Base.connection.execute "UPDATE presences set status = #{params[:status]} WHERE room_id = #{params[:room_id]} AND student_id = #{params[:student_id]} AND month = #{params[:month]}"
    edit
  end

  def fix
    @room = Room.find(params[:room_id])
    @room.students.each do |s|
      presences = Presence.all(:conditions => "student_id = #{s.id} AND room_id = #{@room.id} AND month = #{params[:month]}")
      if presences.count == 0
        Presence.create_presences(:room_id => @room.id, :student_id => s.id, :month => params[:month])
      end
    end
    flash[:success] = t('presence_list.fixed')
    redirect_to :back
  end

protected

  def get_presence_list_data
    presences = Presence.all(:conditions => "room_id = #{params[:room_id]} AND month = #{params[:month]}", :order => "student_id ASC")
  
    i = 0
    
    @students.each do |s|
      @presences << {} 
      @presences[i][:student] = s.name
      @presences[i][:student_id] = s.id
      @lecture_days.each do |l|
        presences.each do |p|
          @presences[i][l.id] = p if (l.id == p.lecture_day_id && p.student_id == s.id)
        end
      end
      i += 1
    end
  end

  def get_data_for_show_presence_list
  end
end

app/views/presences_list/_edit.html.haml
- if @type == 0
  = render 'edit_presence_list'
- else
  = render 'show_presence_list'

app/views/presences_list/_edit_presence_list.html.haml
:javascript
  function update_frequency(row,frequency_row)
    {
      var row = $(row);
      var value = 0;
      var total = 0
  
      row.find('[type=checkbox]').each(function()
      {
         if (($(this).is(':checked')) && (!$(this).hasClass('disabled'))){
          value += 1;  
         }
         if ( !$(this).hasClass('disabled') ){
          total += 1; 
         }
      });
  
      percentage = ((value * 100)/total).toFixed(2);
      if (percentage >= 75){
        style = 'color:green;'
      }
      else{
        style = 'color:red;' 
      }
      if (isNaN(percentage)){
        percentage = 0;
      }
      
      $(frequency_row).html('<div style='+style+'>'+percentage+'%'+'</div>');
    }

    $("tbody tr:nth-child(even)").addClass("even");
    $("tbody tr:nth-child(odd)").addClass("odd");
- if @presences.count == 0
  .div{:style => 'margin: 10px; float:left; clear: both;'}
    Não há atividades ou estudantes cadastrado nesta turma.
- else
  .actions
    - if can? :update, :presences
      = link_to "Fechar lista de presença", finish_presence_list_path(:month => params[:month], :room_id => params[:room_id]), :id => "close_presence_list", :remote => true, :confirm => t('are_you_sure')
  %ul#presence_list_header
    %li
      %b Núcleo:
      = @core.name
    %li
      %b Turma:
      = @room.name
    %li
      %b Nome do alfabetizador:
      = @educators
    %li 
      %b Mês:
      = @month
    %li
      %b Dias de funcionamento:
      - @lecture_days.each do |l|
        - if l != @lecture_days.last
          = "#{l.lecture_on_to_date.try(:strftime, '%d')},"
        - else
          = l.lecture_on_to_date.try(:strftime, '%d')
    

  %ul.presence_list_legend
    %li 
      %label Aula cancelada
      %span.cancelled_class
    %li 
      %label Ausente
      %span.away
    %li 
      %label Evadido
      %span.evaded

  %table{:id => 'presence_list'}
    %thead
      %tr
        %td Alfabetizando
        - @lecture_days.each do |l|
          %td= link_to l.lecture_on_to_date.try(:strftime, '%d'), "#", :alt => "#{l.period}", :title => "#{l.period}", :class => "lecture_day_link"
        %td
    %tbody
      - fix_presence_list = false
      - @presences.each do |p|
        %tr{:id => "#{p[:student_id]}"}
          %td.student
            = link_to p[:student], student_path(:id => p[:student_id]), :target => "_blank"
            - status = p[@lecture_days.first.id].try(:status)
            - if !status.blank?
              - if status > Presence::WITH_CLASS
                .more_info_wrapper
                  %a{:href=> "#", :id => "show_comments_#{p[:student_id]}"}
                    .more_info
                    :javascript
                      $(document).ready(function() {
                        $("#show_comments_#{p[:student_id]}").click(function() {
                          $.ajax({url: "/students/#{p[:student_id]}/presence_list_comments?month=#{params[:month]}"}); 
                        });
                      });
            - if cannot? :update, :presences
              - select_disabled = true
            = select_tag :student_status, options_for_select(Presence::STUDENT_STATUS, :selected => status), :disabled => select_disabled, :class => "student_status", :id => "#{params[:room_id]}_#{params[:month]}_#{p[:student_id]}"

          - @lecture_days.each do |l|
            - presence = p[l.id]
            - if !presence.nil?
              = fields_for presence do |f|
                - style_class = ''
                - checkbox_class = ''
                - case presence.status
                  - when Presence::AWAY
                    - disabled = true
                    - klass = 'disabled'
                    - style_class = 'away'
                  - when Presence::EVADED
                    - disabled = true
                    - klass = 'disabled'
                    - style_class = 'evaded'
                - if !presence.has_class
                  - disabled = true
                  - klass = 'disabled'
                  - checkbox_class = 'disabled'
                  - style_class = ''
                - if cannot? :update, :presences
                  - disabled = true

                %td{:class => "#{klass} #{style_class}"}= f.check_box :presence, :id => "presence_#{presence.id}", :disabled => disabled, :class => checkbox_class
                :javascript
                  $(document).ready(function() {
                    update_frequency("##{p[:student_id]}", '##{p[:student_id]}_frequency');
                    $("#presence_#{presence.id}").change(function() {
                      if ($("#presence_#{presence.id}").is(':checked')){
                        $.ajax({url: "/update_presence/#{presence.id}/1"});
                      }
                      else{
                        $.ajax({url: "/update_presence/#{presence.id}/0"}); 
                      }
                      update_frequency("##{p[:student_id]}", '##{p[:student_id]}_frequency');
                    });
                  });
            - else
              - fix_presence_list = true
              %td

          %td{:id => "#{p[:student_id]}_frequency"}
- if fix_presence_list
  - if can? :update, :presences
    = link_to 'Arrumar lista de presença', fix_presence_list_path(:room_id => @room.id, :month => @month), :class => 'fix_presence_list'
:javascript
  $(document).ready(function() {
    $(".student_status").change(function() {
      var id = $(this).prop("id");
      var array = id.split("_");
      var room_id = array[0];
      var month = array[1];
      var student_id = array[2];
      var status = $(this).val();
      $.ajax({url: "/update_student_presences/"+room_id+"/"+month+"/"+student_id+"/"+status}); 
    });
  });

app/views/presences_list/_show_presence_list.html.haml
:javascript
  $("tbody tr:nth-child(even)").addClass("even");
  $("tbody tr:nth-child(odd)").addClass("odd");
- if current_user.admin?
  .actions
    = link_to "Reabrir lista de presença", reopen_presence_list_path(:month => params[:month], :room_id => params[:room_id]), :id => "close_presence_list", :remote => true, :confirm => t('are_you_sure')

%ul#presence_list_header
  %li
    %b Núcleo:
    = @core.name
  %li
    %b Turma:
    = @room.name
  %li
    %b Nome do alfabetizador:
    = @educators
  %li 
    %b Mês:
    = @month
  %li
    %b Dias de funcionamento:
    - @lecture_days.each do |l|
      - if l != @lecture_days.last
        = "#{l.lecture_on_to_date.try(:strftime, '%d')},"
      - else
        = l.lecture_on_to_date.try(:strftime, '%d')


%ul.presence_list_legend
  %li 
    %label Aula cancelada
    %span.cancelled_class
  %li 
    %label Ausente
    %span.away
  %li 
    %label Evadido
    %span.evaded
%table{:id => 'presence_list'}
  %thead
    %tr
      %td Alfabetizando
      - @lecture_days.each do |l|
        %td= link_to l.lecture_on_to_date.try(:strftime, '%d'), "#", :alt => "#{l.period}", :title => "#{l.period}", :class => "lecture_day_link"
      %td
  %tbody
    - @presence_list.each do |pp|
      - presences = pp.presences.split(',')
      %tr
        %td.student
          = link_to pp.student.name, student_path(:id => pp.student_id), :target => "_blank"
          - status = Presence.find(presences.first).status.to_i
          - if status > Presence::WITH_CLASS
            .more_info_wrapper
              %a{:href=> "#", :id => "show_comments_#{pp.student_id}"}
                .more_info
                :javascript
                  $(document).ready(function() {
                    $("#show_comments_#{pp.student_id}").click(function() {
                      $.ajax({url: "/students/#{pp.student_id}/#{params[:month]}/show_presence_list_comments"}); 
                      return false;
                    });
                  });

          - presences.each do |p|
            - presence = Presence.find(p)
            - style_class = ''
            - checkbox_class = ''
            - case presence.status
              - when Presence::AWAY
                - disabled = true
                - klass = 'disabled'
                - style_class = 'away'
              - when Presence::EVADED
                - disabled = true
                - klass = 'disabled'
                - style_class = 'evaded'
            - if !presence.has_class
              - disabled = true
              - klass = 'disabled'
              - checkbox_class = 'disabled'
              - style_class = ''

            - if presence.presence
              %td{:class => "#{klass} #{style_class}"}
                %b X 
            - else
              %td{:class => "#{klass} #{style_class}"}
          - if pp.presence >= 75
            - color = "green"
          - else
            - color = "red"
          %td{:style => "color: #{color}"}= "#{pp.presence}%"

app/views/presences_list/edit.js.haml
$(".calendar").css("background-image", "url('/images/calendar.png')"); 
$("#calendar_#{@month}").css("background-image", "url('/images/calendar_actived.png')"); 
$("#presence_list_area").html("#{escape_javascript(render 'edit')}")

app/views/presences_list/finish.js.haml
$("#presence_list_area").html("#{escape_javascript(render 'edit')}")

app/views/presences_list/index.html.haml
%h1.title= "Atualização das listas de presença da turma #{@room.name}"
.action_back 
  = link_to t('back'), :rooms, :class => 'back_link'
  .presence_lists= link_to "Ver Dias de Aula", room_lecture_days_path(:room_id => params[:room_id])
.presence_list
  .calendar
    .year 2012
  - @months.each do |m|
    %div{:id => "calendar_#{m}", :class => "calendar"}
      .month= link_to show_month(m), edit_presences_list_path(:room_id => params[:room_id], :month => m), :remote => true, :class => "show_presence_list"
#presence_list_area

:javascript
  $(document).ready(function() {
    $('.show_presence_list').click(function() {
      $("#presence_list_area").html("")
      show_spinner('presence_list_area');
    });
    
  });

  

app/views/presences_list/reopen.js.haml
$("#presence_list_area").html("#{escape_javascript(render 'edit')}")

app/views/presences_list/update_student_presences.js.haml
- if params[:status].to_i > Presence::ACTIVE
  $.ajax({url: "/students/#{params[:student_id]}/presence_list_comments/new?month=#{params[:month]}"}); 
$("#presence_list_area").html("#{escape_javascript(render 'edit')}")