config/routes.rb
# -*- encoding : utf-8 -*-
Alfa::Application.routes.draw do

  resources :occupations

  resources :world_readings

  resources :students do
    resources :presence_list_comments
  end

  resources :rooms do
    resources :lecture_days
  end

  root :to => "cores#index"
  resources :cores
  resources :coordinators
  resources :educators
  resources :users
  resources :user_sessions
  match 'sign_up' => 'users#sign_up', :as => 'sign_up'
  match 'sign_in' => 'user_sessions#new', :as => 'sign_in'
  match 'sign_out' => 'user_sessions#destroy', :as => 'sign_out'
  match 'update_city' => 'cores#update_city', :as => 'update_city'
  match 'update_rooms/:educator_id/:core_id' => 'educators#update_rooms', :as => 'update_rooms'
  match 'student_update_rooms/:student_id/:core_id' => 'students#update_rooms', :as => 'student_update_rooms'
  match 'coordinator_update_rooms/:coordinator_id/:core_id' => 'coordinators#update_rooms', :as => 'coordinator_update_rooms'
  match 'students_without_mother_name' => 'students#without_mother_name', :as => 'without_mother_name'
  match 'update_cancelled/:id' => 'lecture_days#update_cancelled', :as => 'update_cancelled'
  match 'new_lecture_day/:room_id' => 'lecture_days#new_lecture_day', :as => 'new_lecture_day'
  match ':room_id/:month/fix_presence_list' => 'presences_list#fix', :as => 'fix_presence_list'
  match ':room_id/:month/finish_presence_list' => 'presences_list#finish', :as => 'finish_presence_list'
  match ':room_id/:month/reopen_presence_list' => 'presences_list#reopen', :as => 'reopen_presence_list'
  match ':room_id/presences_list' => 'presences_list#index', :as => 'presences_list'
  match ':room_id/:month/presences_list' => 'presences_list#edit', :as => 'edit_presences_list'
  match 'update_presence/:id/:status' => 'presences_list#update', :as => 'update_presence'
  match 'update_student_presences/:room_id/:month/:student_id/:status' => 'presences_list#update_student_presences', :as => 'update_student_presences'
  match 'reports' => 'reports#index', :as => 'reports'
  match 'show_report' => 'reports#show', :as => 'show_report'
  match 'report_update_rooms/:core_id' => 'reports#update_rooms', :as => 'report_update_rooms'
  match 'show_full_report' => 'reports#show_full_report', :as => 'show_full_report'

  match 'show_second_report/:column/:second_column/:core_id/:room_id' => 'reports#show_second_report', :as => 'show_second_report'
  match 'students/:student_id/:month/show_presence_list_comments' => 'presence_list_comments#show', :as => 'show_presence_list_comments'
  
end

app/models/core.rb
# -*- encoding : utf-8 -*-
class Core < ActiveRecord::Base

#relationships
  has_many :rooms
  has_many :educators
  has_many :phones
  has_and_belongs_to_many :coordinators
  has_and_belongs_to_many :desk_types
  has_many :partner_resources, :through => :cores_partner_resources
  has_many :cores_partner_resources
  has_many :seat_types, :through => :cores_seat_types
  has_many :cores_seat_types
  has_many :displacements, :through => :cores_displacements
  has_many :cores_displacements
  belongs_to :city
  has_many :periods

#validations

  validates :computer_observation, :kitchen_observation, :resources_observation, :place_description, :length => { :maximum => 100 }

#constants

  SIZES = [[I18n.t('core.size.until_20'), 0], [I18n.t('core.size.between_20_30'), 1], [I18n.t('core.size.up_30'), 2]]
  BOARD_TYPES =  [[I18n.t('core.board_type.blackboard'), 0], [I18n.t('core.board_type.whiteboard'), 1]]
  PLACES = [[I18n.t('core.place.association'), 0], [I18n.t('core.place.church_hall'), 1],
    [I18n.t('core.place.cooperative'), 2], [I18n.t('core.place.union'), 3],
    [I18n.t('core.place.cruch'), 4], [I18n.t('core.place.outdoor'), 5], [I18n.t('other'), 6]]
  COMMUNITY_TYPES = [[I18n.t('core.community_type.rural'), 1], [I18n.t('core.community_type.urban'), 2], ['Pesca Marinha (Mar)', 0], ['Pesca Ribeirinha (Rio)', 3], ['Outra', 4]]
  ILLUMINATION_TYPES = [[I18n.t('core.illumination_type.electric_power'), 0],
    [I18n.t('core.illumination_type.lamp'), 1], [I18n.t('core.illumination_type.other'), 2]]
  ILLUMINATION_CONDITIONS = [[I18n.t('core.illumination_condition.ok'), 0],
    [I18n.t('core.illumination_condition.nok'), 1]]
  TOTAL_SEATS = [[I18n.t('core.total_seats.until_10'), 0], [I18n.t('core.total_seats.between_10_20'), 1], ["Acima de 20", 2]]

#nested attributes

  accepts_nested_attributes_for :partner_resources, :reject_if => lambda { |a| a[:resource].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :phones, :reject_if => lambda { |a| a[:number].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :seat_types , :reject_if => lambda { |a| a[:seat_type].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :periods, :reject_if => lambda { |a| a[:day_of_week].blank? }, :allow_destroy => true

  def size_to_s
    get_attribute_value(self.size, SIZES)
  end

  def board_type_to_s
    get_attribute_value(self.board_type, BOARD_TYPES)
  end

  def place_to_s
    get_attribute_value(self.place, PLACES)
  end

  def community_type_to_s
    get_attribute_value(self.community_type, COMMUNITY_TYPES)
  end

  def illumination_type_to_s
    get_attribute_value(self.illumination_type, ILLUMINATION_TYPES)
  end

  def illumination_condition_to_s
    get_attribute_value(self.illumination_condition, ILLUMINATION_CONDITIONS)
  end

  def total_seats_to_s
    get_attribute_value(self.total_seats, TOTAL_SEATS)
  end

private

  def get_attribute_value(attribute, array)
    array.each do |a|
      return a.first if a.last == attribute
    end
    ''
  end
end

app/controllers/cores_controller.rb
# -*- encoding : utf-8 -*-
class CoresController < ApplicationController

  load_and_authorize_resource
  skip_authorize_resource :only => :update_city
  before_filter :load_data, :only => [:edit, :new, :update, :create]
  # GET /cores
  # GET /cores.xml

  def update_city
    session[:city_id] = params[:city]
  end


  def index
    if current_user.try(:educator_id).blank?
      @cores = Core.all(:conditions => "city_id IN (#{@cities_ids})", :include => [:city], :order => "name ASC")
    else
      @cores = [current_user.educator.core]
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cores }
    end
  end

  # GET /cores/1
  # GET /cores/1.xml
  def show
    @core = Core.first(:conditions => "id = #{params[:id]}")
    if @core.nil?
      redirect_to cores_path 
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @core }
      end
    end
  end

  # GET /cores/new
  # GET /cores/new.xml
  def new
    @core = Core.new
    @core.phones.build
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @core }
    end
  end

  # GET /cores/1/edit
  def edit
    @core = Core.find(params[:id], :include => [:cores_displacements, :cores_partner_resources, :cores_seat_types])

    @core.cores_partner_resources.each do |c|
      @resource_desc = c.resource_desc if !c.resource_desc.nil?
    end

    @core.cores_seat_types.each do |c|
      @seat_type_desc = c.seat_type_desc if !c.seat_type_desc.nil?
    end

    @core.cores_displacements.each do |c|
      @displacement_desc_0 = c.displacement_desc if !c.displacement_desc.nil? && c.displacement_type == 0
      @displacement_desc_1 = c.displacement_desc if !c.displacement_desc.nil? && c.displacement_type == 1
    end

  end

  # POST /cores
  # POST /cores.xml
  def create
    @core = Core.new(params[:core])
    seat_type_desc = params[:seat_type_desc]
    resource_desc = params[:resource_desc]

    respond_to do |format|
      if @core.save
        CoresDisplacement.create_displacements(params[:displacement_ids], @core.id,
          params[:displacement_desc_0], params[:displacement_desc_1])
        CoresSeatType.update_seat_type_desc(seat_type_desc, @core.id) if !seat_type_desc.blank?
        CoresPartnerResource.update_resource_desc(resource_desc, @core.id) if !resource_desc.blank?
        flash[:success] = t('core.created')
        format.html { redirect_to(cores_path) }
        format.xml  { render :xml => @core, :status => :created, :location => @core }
      else
        flash[:error] = t('default_error_message')
        format.html { render :action => "new" }
        format.xml  { render :xml => @core.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cores/1
  # PUT /cores/1.xml
  def update
    @core = Core.find(params[:id])
    seat_type_desc = params[:seat_type_desc]
    resource_desc = params[:resource_desc]
    respond_to do |format|
      if @core.update_attributes(params[:core])
        CoresSeatType.update_seat_type_desc(seat_type_desc, @core.id) if !seat_type_desc.blank?
        CoresPartnerResource.update_resource_desc(resource_desc, @core.id) if !resource_desc.blank?
        flash[:success] = t('core.updated')
        format.html { redirect_to(cores_path) }
        format.xml  { head :ok }
      else
        flash[:error] = t('default_error_message')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @core.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cores/1
  # DELETE /cores/1.xml
  def destroy
    @core = Core.find(params[:id])
    @core.destroy

    respond_to do |format|
      format.html { redirect_to(cores_url) }
      format.xml  { head :ok }
    end
  end

  def load_data
    @displacements = Displacement.all
    @desk_types = DeskType.all
    @cities = City.all(:conditions => "id IN (#{@cities_ids})").collect{|c| [c.name, c.id]}
  end
end

app/helpers/cores_helper.rb
# -*- encoding : utf-8 -*-
module CoresHelper



end

app/views/cores/_desk_types_fields.html.haml
%label= t('core.desk_type_field')
%br/
- @desk_types.each do |d|
  = check_box_tag 'core[desk_type_ids][]', d.id, @core.desk_types.include?(d)
  = d.desk_type

app/views/cores/_displacement_fields.html.haml
%b= t('core.displacement_title')
%br/
.field_with_complement_info
  = t('core.educators')
  %br/
  - @displacements.each do |d|
    = check_box_tag 'displacement_ids[]', "#{d.id}.0", @core.displacements.include?(d), :id => "displacement_id_0_#{d.id}"
    = d.displacement
:javascript
  $(document).ready(function() {
      $("#displacement_id_0_9").change(function() {
          if ($("#displacement_id_0_9").is(':checked')){
            jQuery('#core_displacement_desc_0_div').attr('style','display:block; !important');
            jQuery('#displacement_desc_0').focus();
          }
          else{
            jQuery('#core_displacement_desc_0_div').attr('style','display:none; !important');
          }
      });
  });
#core_displacement_desc_0_div.invisible
  = label_tag :displacement_desc, t('which')
  %br/
  = text_field_tag :displacement_desc_0, @displacement_desc_0, :id => "displacement_desc_0"
%br/
.field_with_complement_info
  = t('core.students')
  %br/
  - @displacements.each do |d|
    = check_box_tag 'displacement_ids[]', "#{d.id}.1" , @core.displacements.include?(d), :id => "displacement_id_1_#{d.id}"
    = d.displacement
:javascript
  $(document).ready(function() {
      $("#displacement_id_1_9").change(function() {
          if ($("#displacement_id_1_9").is(':checked')){
            jQuery('#core_displacement_desc_1_div').attr('style','display:block; !important');
            jQuery('#displacement_desc_1').focus();
          }
          else{
            jQuery('#core_displacement_desc_1_div').attr('style','display:none; !important');
          }
      });
  });
#core_displacement_desc_1_div.invisible
  = label_tag :displacement_desc, t('which')
  %br/
  = text_field_tag :displacement_desc_1, @displacement_desc_1, :id => "displacement_desc_1"

app/views/cores/_form.html.haml
:javascript
  $(document).ready(function() {
    show_field("#core_place", '#core_place_desc_div', 'select', 6)
    show_field("#core_illumination_type", '#core_illumination_type_desc_div', 'select', 2)
    show_field("#core_community_type", '#core_community_type_desc_div', 'select', 4)

    var checkbox_fields = [
        ["#partner_resource_id_1", '#core_resource_desc_div'],
        ["#seat_type_id_1", '#core_seat_type_desc_div'],
        ["#displacement_id_0_9", '#core_displacement_desc_0_div'],
        ["#displacement_id_1_9", '#core_displacement_desc_1_div'],
        ["#core_another_place_true", '#core_another_place_desc_div'],
        ["#core_board_true", '#board_type_div'],
        ["#core_has_restroom_true", '#total_restroom_div'],
        ["#core_has_computers_true", '#total_computers_div']
      ];

    checkbox_fields.forEach(function(field) {  
      show_field(field[0], field[1], 'checkbox', '')
    });  
    
  });

= semantic_form_for(@core, :html => {:id => 'formframe'}) do |f|
  - if @core.errors.any?
    #error_explanation
      %ul
        - @core.errors.full_messages.each do |msg|
          %li= msg
  %div
    = f.label :name, 'Localidade'
    %br
    = f.text_field :name
  %div{:style => hidden_fields}
    = f.label :place_description, 'Identificação do espaço'
    %br
    = f.text_area :place_description, :cols => 100, :rows => 5
    = f.hidden_field :city_id, :value => session[:city_id]
  %div
    = f.label :community, t('core.community')
    %br
    = f.text_field :community
  %div
    = f.label :address, t('core.address')
    %br
    = f.text_field :address, :size => 100
  %div{:style => hidden_fields}
    = f.label :number, 'Número'
    %br
    = f.text_field :number
  %div{:style => hidden_fields}
    = f.label :zip_code, 'CEP'
    %br
    = f.text_field :zip_code
    :javascript
        $(document).ready(function() {
          $("#core_zip_code").mask("99999-999");
        });

  %div
    .field_with_complement_info
      = f.label :community_type, t('core.community_field')
      %br
      = f.select :community_type, Core::COMMUNITY_TYPES, :prompt => "Selecione"
      %div{:style => hidden_fields}
        #core_community_type_desc_div.invisible
          = f.label :community_type_desc, t('which')
          = f.text_field :community_type_desc
        :javascript
          $(document).ready(function() {
              $("#core_community_type").change(function() {
                  var value = $(this).val();
                  if (value == 4){
                    jQuery('#core_community_type_desc_div').attr('style','display:block; !important');
                    jQuery('#core_community_type_desc').focus();
                  }
                  else{
                    jQuery('#core_community_type_desc_div').attr('style','display:none; !important');
                  }
              });
          });
  %div
    = f.label :place, t('core.place_field')
    %br
    .field_with_complement_info
      = f.select :place, Core::PLACES, :prompt => "Selecione"
      :javascript
        $(document).ready(function() {
            $("#core_place").change(function() {
                var value = $(this).val();
                if (value == 6){
                  jQuery('#core_place_desc_div').attr('style','display:block; !important');
                  jQuery('#core_place_desc').focus();
                }
                else{
                  jQuery('#core_place_desc_div').attr('style','display:none; !important');
                }
            });
        });
    #core_place_desc_div.invisible
      = f.label :place_desc, t('which')
      = f.text_field :place_desc
  %div
    .gray_border
      %h2= t('core.period_field')
    %br
    - f.fields_for :periods do |builder|
      = render "period_fields", :f => builder
    %div
      .form_actions
        .add
          = link_to_add_fields t('period.new'), f, :periods
  %div
    = render "partner_resources_fields"
  %div{:style => hidden_fields}
    = f.label :resources_observation, "Observação"
    %br
    = f.text_area :resources_observation, :cols => 100, :rows => 5
  %div
    = f.label :institution_name, t('core.name_field')
    %br
    = f.text_field :institution_name
  %div
    = f.label :responsible, t('core.responsible_field')
    %br
    = f.text_field :responsible
  %div
    .gray_border
      %h2= t('core.phones_field')
    %br
    - f.fields_for :phones do |builder|
      = render "/layouts/shared/phone_fields", :f => builder
    %div
    .form_actions
      .add
        = link_to_add_fields t('phone.new'), f, :phones, "/layouts/shared/"
    
  %div
    = f.label :email, t('core.email_field')
    %br
    = f.text_field :email
  %div
    = f.label :main_activity, t('core.main_activity_field')
    %br
    = f.text_field :main_activity, :size => 100
  %div
    .gray_border
      %h2= t('core.physical_conditions_field')
    %br
    = f.label :size, t('core.size.title')
    %br
    = f.select :size, Core::SIZES, :prompt => "Selecione"
  %div
    = f.input :board, :as => :radio, :collection => [[t('yyes'), true], [t('nno'), false]]
    :javascript
      $(document).ready(function() {
          $("#core_board_true").change(function() {
              if ($("#core_board_true").is(':checked')){
                jQuery('#board_type_div').attr('style','display:block; !important');
                jQuery('#core_board_type').focus();
              }
          });
          $("#core_board_false").change(function() {
              if ($("#core_board_false").is(':checked')){
                jQuery('#board_type_div').attr('style','display:none; !important');
              }
          });
          
      });
  %div
    #board_type_div{:style => "display: none;"}
      = f.label :board_type, t('core.board_type_field')
      %br
      = f.select :board_type, Core::BOARD_TYPES, :prompt => "Selecione"
  %div
    = render "seat_types_fields"
    %div
      = f.label :total_seats, t('core.total_seats_field')
      %br
      = f.select :total_seats, Core::TOTAL_SEATS, :prompt => "Selecione"
    %div
      = render "desk_types_fields"
    %div
      = f.label :illumination_type, t('core.illumination_field')
      %br
      .field_with_complement_info
        = f.select :illumination_type, Core::ILLUMINATION_TYPES, :prompt => "Selecione"
        :javascript
          $(document).ready(function() {
              $("#core_illumination_type").change(function() {
                  var value = $(this).val();
                  if (value == 2){
                    jQuery('#core_illumination_type_desc_div').attr('style','display:block; !important');
                    jQuery('#core_illumination_type_desc').focus();
                  }
                  else{
                    jQuery('#core_illumination_type_desc_div').attr('style','display:none; !important');
                  }
              });
          });
      #core_illumination_type_desc_div.invisible
        = f.label :illumination_type_desc, t('which')
        = f.text_field :illumination_type_desc
    %div
      = f.label :illumination_condition, t('core.illumination_condition_field')
      %br
      = f.select :illumination_condition, Core::ILLUMINATION_CONDITIONS, :prompt => "Selecione"
    %div
      .field_with_complement_info
        = f.input :another_place, :as => :radio, :collection => [[t('yyes'), true], [t('nno'), false]]
        :javascript
          $(document).ready(function() {
              $("#core_another_place_true").change(function() {
                  if ($("#core_another_place_true").is(':checked')){
                    jQuery('#core_another_place_desc_div').attr('style','display:block; !important');
                    jQuery('#another_place_desc').focus();
                  }
                  else{
                    jQuery('#core_another_place_desc_div').attr('style','display:none; !important');
                  }
              });
              $("#core_another_place_false").change(function() {
                  if ($("#core_another_place_false").is(':checked')){
                    jQuery('#core_another_place_desc_div').attr('style','display:none; !important');
                  }
              });
          });
      #core_another_place_desc_div.invisible
        = f.label :another_place_desc, t('which_s')
        = f.text_field :another_place_desc
    .textarea_div
      = f.label :coordenation_analysis, t('core.coordenation_analysis_field')
      %br
      = f.text_area :coordenation_analysis, :cols => 100, :rows => 5
    %div
      = f.label :visit_on, t('core.visit_on_field')
      %br
      = f.date_select :visit_on, :prompt => "Selecione"
    %div
      = f.label :who_visited, t('core.who_visited_field')
      %br
      = f.text_field :who_visited
    %div
      .field_with_complement_info
        = f.input :has_restroom, :as => :radio, :collection => [[t('yyes'), true], [t('nno'), false]]
        :javascript
          $(document).ready(function() {
              $("#core_has_restroom_true").change(function() {
                  if ($("#core_has_restroom_true").is(':checked')){
                    jQuery('#total_restroom_div').attr('style','display:block; !important');
                    jQuery('#core_total_restroom').focus();
                  }
              });
              $("#core_has_restroom_false").change(function() {
                  if ($("#core_has_restroom_false").is(':checked')){
                    jQuery('#total_restroom_div').attr('style','display:none; !important');
                  }
              });
              
          });
      %div{:style => hidden_fields}
        #total_restroom_div.invisible
          = f.label :total_restroom, 'Quantos'
          = f.text_field :total_restroom
    %div{:style => hidden_fields}
      .field_with_complement_info
        = f.input :has_kitchen, :as => :radio, :collection => [[t('yyes'), true], [t('nno'), false]]
    %div{:style => hidden_fields}
      = f.label :kitchen_observation, "Observação"
      %br
      = f.text_area :kitchen_observation, :cols => 100, :rows => 5
    %div{:style => hidden_fields}
      .field_with_complement_info
        = f.input :has_computers, :as => :radio, :collection => [[t('yyes'), true], [t('nno'), false]]
        :javascript
          $(document).ready(function() {
              $("#core_has_computers_true").change(function() {
                  if ($("#core_has_computers_true").is(':checked')){
                    jQuery('#total_computers_div').attr('style','display:block; !important');
                    jQuery('#core_total_computers').focus();
                  }
              });
              $("#core_has_computers_false").change(function() {
                  if ($("#core_has_computers_false").is(':checked')){
                    jQuery('#total_computers_div').attr('style','display:none; !important');
                  }
              });
              
          });
        #total_computers_div.invisible
          = f.label :total_computers, 'Quantos'
          = f.text_field :total_computers
    %div{:style => hidden_fields}
      = f.label :computer_observation, "Observação"
      %br
      = f.text_area :computer_observation, :cols => 100, :rows => 5

    .actions
      = f.submit button

app/views/cores/_partner_resources_fields.html.haml
%label
  = t('core.partner_title')
.field_with_complement_info
  = t('core.partner_resource_field')
  %br/
  - PartnerResource.all.each do |p|
    = check_box_tag 'core[partner_resource_ids][]', p.id, @core.partner_resources.include?(p), :id => "partner_resource_id_#{p.id}"
    = p.resource
:javascript
  $(document).ready(function() {
      $("#partner_resource_id_1").change(function() {
          if ($("#partner_resource_id_1").is(':checked')){
            jQuery('#core_resource_desc_div').attr('style','display:block; !important');
            jQuery('#resource_desc').focus();
          }
          else{
            jQuery('#core_resource_desc_div').attr('style','display:none; !important');
          }
      });
  });
#core_resource_desc_div.invisible
  %label= t('which')
  = text_field_tag :resource_desc, @resource_desc

app/views/cores/_period_fields.html.haml
%br
.fields
  .fields_wrapper
    .form_actions
      .delete
        = link_to_remove_fields t('remove'), f
    .period_fields
      = t('period.day_of_week')
      = f.select :day_of_week, Period::DAYS_OF_WEEK, :prompt => t('select')
      = t('period.start_time')
      = f.time_select :start_time, {:minute_step => 10}, :prompt => t('select')
      = t('period.end_time')
      = f.time_select :end_time, {:minute_step => 10}, :prompt => t('select')

app/views/cores/_seat_types_fields.html.haml
.field_with_complement_info
  %label= t('core.seat_type_field')
  %br/
  - SeatType.all.each do |s|
    = check_box_tag 'core[seat_type_ids][]', s.id, @core.seat_types.include?(s), :id => "seat_type_id_#{s.id}"
    = s.seat_type
:javascript
  $(document).ready(function() {
      $("#seat_type_id_1").change(function() {
          if ($("#seat_type_id_1").is(':checked')){
            jQuery('#core_seat_type_desc_div').attr('style','display:block; !important');
            jQuery('#seat_type_desc').focus();
          }
          else{
            jQuery('#core_seat_type_desc_div').attr('style','display:none; !important');
          }
      });
  });
#core_seat_type_desc_div.invisible
  = label_tag :seat_type_desc, t('seat_type.which_material')
  %br/
  = text_field_tag :seat_type_desc, @seat_type_desc

app/views/cores/edit.html.haml
%h1.title= t('core.edit')
.action_back 
  = link_to t('back'), cores_path, :class => 'back_link'
= render 'form', :button => t('update')

app/views/cores/index.html.haml
:javascript
  $(document).ready(function(){
    $('a.more').click(function(){
      $(this).parent().parent().next().children().children().slideToggle();
      return false;
    })
  });


%h1.title= t('core.listing')
.actions 
  = render '/layouts/shared/add_button', :new_label=>t('core.new'), :new_path => new_core_path, :permission => :cores
= render '/layouts/shared/filter_bar'
%table{:class => 'list'}
  %thead
    %tr
      %th= t('core.name')
      %th= t('core.community')
      %th{:style => 'width: 20px;'}
      %th{:style => 'width: 20px;'}
  %tbody
    - @cores.each do |core|
      %tr{:class => 'more-click'}
        %td{:class => 'first-td'}=  raw"<a href='#' class='more'></a> #{core.name}"
        %td= core.community
        = render '/layouts/shared/edit_delete', :edit_path => edit_core_path(core), :delete_obj => core, :permission => :cores
      %tr{:class => 'more-info'}
        %td{:colspan => 4}
          %div
            = render 'show', :core => core
%br

app/views/cores/show.html.haml
= link_to t('edit'), edit_core_path(@core)
|
\#{link_to t('back'), cores_path}
%br
%p
  %b= 'Nome do núcleo'
  = @core.name
  %br
  %b= t('core.city')
  = @core.city.try(:name)
  %br
  %b= t('core.community') 
  = @core.community
  %br
  %b= t('core.address') 
  = @core.address
  %br
  %b= t('core.community_type.title')  
  = @core.community_type_to_s
  %br
  %b= t('core.place.title') 
  = @core.place_to_s
  - if !@core.place_desc.blank?
    = "(#{@core.place_desc})"
  %br
  %b= t('core.name')  
  = @core.institution_name
  %br
  %b= t('core.responsible') 
  = @core.responsible
  %br
  %b= t('core.email') 
  = @core.email
  %br
  %b= t('core.main_activity') 
  = @core.main_activity  
  %br
  - if @core.board
    %b= t('core.board') 
    = "#{@core.board_type_to_s} (#{@core.size_to_s})"
  %br
  %b= t('core.total_seats.title')
  = @core.total_seats_to_s
  %br
  %b= t('core.illumination_type.title')
  = @core.illumination_type_to_s
  - if !@core.illumination_type_desc.blank?
    = " (#{@core.illumination_type_desc})"
  %br
  %b= t('core.illumination_condition.title')
  = @core.illumination_condition_to_s
  %br
  %b= t('core.another_place')
  = @core.another_place
  - if !@core.another_place_desc.blank?
    = @core.another_place_desc
  %br
  %b= t('core.coordenation_analysis_field')
  = @core.coordenation_analysis
  %br
  %b= t('core.visit_on_field')
  = @core.visit_on.try(:strftime, '%d/%m/%Y')
  %br
  %b= t('core.who_visited_field')
  = @core.who_visited

app/views/cores/update_city.js.haml
location.reload();