config/routes.rb
# -*- encoding : utf-8 -*-
Alfa::Application.routes.draw do

  resources :occupations

  resources :world_readings

  resources :students do
    resources :presence_list_comments
  end

  resources :rooms do
    resources :lecture_days
  end

  root :to => "cores#index"
  resources :cores
  resources :coordinators
  resources :educators
  resources :users
  resources :user_sessions
  match 'sign_up' => 'users#sign_up', :as => 'sign_up'
  match 'sign_in' => 'user_sessions#new', :as => 'sign_in'
  match 'sign_out' => 'user_sessions#destroy', :as => 'sign_out'
  match 'update_city' => 'cores#update_city', :as => 'update_city'
  match 'update_rooms/:educator_id/:core_id' => 'educators#update_rooms', :as => 'update_rooms'
  match 'student_update_rooms/:student_id/:core_id' => 'students#update_rooms', :as => 'student_update_rooms'
  match 'coordinator_update_rooms/:coordinator_id/:core_id' => 'coordinators#update_rooms', :as => 'coordinator_update_rooms'
  match 'students_without_mother_name' => 'students#without_mother_name', :as => 'without_mother_name'
  match 'update_cancelled/:id' => 'lecture_days#update_cancelled', :as => 'update_cancelled'
  match 'new_lecture_day/:room_id' => 'lecture_days#new_lecture_day', :as => 'new_lecture_day'
  match ':room_id/:month/fix_presence_list' => 'presences_list#fix', :as => 'fix_presence_list'
  match ':room_id/:month/finish_presence_list' => 'presences_list#finish', :as => 'finish_presence_list'
  match ':room_id/:month/reopen_presence_list' => 'presences_list#reopen', :as => 'reopen_presence_list'
  match ':room_id/presences_list' => 'presences_list#index', :as => 'presences_list'
  match ':room_id/:month/presences_list' => 'presences_list#edit', :as => 'edit_presences_list'
  match 'update_presence/:id/:status' => 'presences_list#update', :as => 'update_presence'
  match 'update_student_presences/:room_id/:month/:student_id/:status' => 'presences_list#update_student_presences', :as => 'update_student_presences'
  match 'reports' => 'reports#index', :as => 'reports'
  match 'show_report' => 'reports#show', :as => 'show_report'
  match 'report_update_rooms/:core_id' => 'reports#update_rooms', :as => 'report_update_rooms'
  match 'show_full_report' => 'reports#show_full_report', :as => 'show_full_report'

  match 'show_second_report/:column/:second_column/:core_id/:room_id' => 'reports#show_second_report', :as => 'show_second_report'
  match 'students/:student_id/:month/show_presence_list_comments' => 'presence_list_comments#show', :as => 'show_presence_list_comments'
  
end

app/models/educator.rb
# -*- encoding : utf-8 -*-
class Educator < ActiveRecord::Base
  belongs_to :core
  has_and_belongs_to_many :professional_exps
  has_and_belongs_to_many :rooms
  has_many :social_participations
  has_many :phones
  has_many :education_exps, :through => :educators_education_exps
  has_many :educators_education_exps

  has_and_belongs_to_many :use_social_net_works
  has_and_belongs_to_many :know_social_net_works
  has_and_belongs_to_many :internet_uses
  has_and_belongs_to_many :pc_uses

  AGE_RANGE = [["De 18 a 29 anos", 1], ["De 30 a 44 anos", 2], ["De 45 a 59 anos", 3], ["Acima de 60 anos", 4]]
  ABOUT_PC_USE = [["Consegue usar sozinho", 1], ["Não sabe usar, mas gostaria de aprender", 2], ["Consegue usar com ajuda de alguém", 3], ["Não sabe usar, não gostaria de aprender", 4]]
  WHERE_USE_PC = [["Lan House", 1], ["Na casa de família", 2], ["Na casa de amigo", 3], ["Outros", 4]]
  WHICH_USES = [["Escrever textos", 1], ["Ouvir música e/ou assistir vídeos", 2], ["Ler textos", 3], ["Acessar a Internet", 4], ["Fazer planilhas", 5], ["Jogar", 6],
    ["Realizar cursos", 7], ["Participar de redes sociais", 8]]
  SPECIAL_NEED = [["Deficiência visual", 1], ["Deficiência física", 2], ["Deficiência auditiva", 3], ["Deficiência intelectual/mental", 4]]
  FOR_WHAT_USE_INTERNET = [["Lazer", 1], ["Estudo", 2], ["Trabalho", 3], ["Outros", 4]]
  SOCIAL_NETWORK = [["Orkut", 1], ["Facebook", 2], ["Twitter", 3], ["Outras", 4]]
  WHERE_HAS_INTERNET = [["Em casa", 1], ["No trabalho", 2], ["Em outros espaços", 3]]

  accepts_nested_attributes_for :phones, :reject_if => lambda { |a| a[:number].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :social_participations, :allow_destroy => true
  
  validates_presence_of :core_id, :name

  def age
    return '' if self.dob.nil?
    value = Date.today.year - self.dob.year
    value -= 1 if (Date.today < self.dob + value.years)
    return value
  end

  def where_use_pc_to_s
    get_attribute_value(self.where_use_pc, WHERE_USE_PC)
  end

  def total_seats_to_s
    get_attribute_value(self.total_seats, Coordinator::TOTAL_SEATS)
  end

  def gender_to_s
    get_attribute_value(self.gender, Coordinator::GENDERS)
  end

  def ethnicity_to_s
    get_attribute_value(self.ethnicity, Coordinator::ETHNICITIES)
  end

  def political_party_to_s
    get_attribute_value(self.political_party, Coordinator::POLITICAL_PARTIES)
  end

  def zone_to_s
    get_attribute_value(self.zone, Coordinator::ZONES)
  end

  def civil_status_to_s
    get_attribute_value(self.civil_status, Coordinator::CIVIL_STATUS)
  end

  def house_to_s
    get_attribute_value(self.civil_status, Coordinator::HOUSES)
  end

  def house_type_to_s
    get_attribute_value(self.civil_status, Coordinator::HOUSE_TYPES)
  end

  def special_need_to_s
    if self.special_need
      "Sim"
    else
      "Não"
    end
  end

  def has_internet_to_s
    if self.has_internet
      "Sim"
    else
      "Não"
    end
  end

  def has_pc_to_s
    if self.has_pc
      "Sim"
    else
      "Não"
    end
  end

  def know_social_network_to_s
    if self.know_social_network
      "Sim"
    else
      "Não"
    end
  end

  def travel_disponibility_to_s
    if self.travel_disponibility
      "Sim"
    else
      "Não"
    end
  end

  def political_affiliation_to_s
    get_attribute_value(self.political_affiliation, Coordinator::POLITICAL_AFFILIATIONS)
  end

  def religion_to_s
    get_attribute_value(self.religion, Coordinator::RELIGIONS)
  end

  def association_to_s
    get_attribute_value(self.association, Coordinator::ASSOCIATIONS)
  end

  def cooperative_to_s
    get_attribute_value(self.cooperative, Coordinator::COOPERATIVES)
  end

  def education_level_to_s
    get_attribute_value(self.education_level, Coordinator::EDUCATION_LEVELS)
  end

  def where_has_internet_to_s
    get_attribute_value(self.where_has_internet, Educator::WHERE_HAS_INTERNET)
  end

  def about_pc_use_to_s
    get_attribute_value(self.about_pc_use, Educator::ABOUT_PC_USE)  
  end

  def internet_access_local_to_s
    get_attribute_value(self.internet_access_local, Student::INTERNET_ACCESS_LOCAL)   
  end

  def familiar_income_to_s
    get_attribute_value(self.familiar_income, Coordinator::FAMILIAR_INCOME)   
  end

  def age_range_to_s
    get_attribute_value(self.age_range, AGE_RANGE)   
  end

  def special_need_type_to_s
    get_attribute_value(self.special_need_type, SPECIAL_NEED)   
  end

  def self.to_csv_file(educators)
    array = []
    educators.each do |r|
      new_array = Array.new
      puts r.name
      new_array << r.id  
      new_array << r.name
      new_array << r.start_date_to_students.try(:strftime, "%d/%m/%Y")
      new_array << r.age
      new_array << r.gender_to_s
      new_array << r.dob.try(:strftime, "%d/%m/%Y") 
      new_array << r.ethnicity_to_s
      new_array << r.hometown
      new_array << r.district  
      new_array << r.number  
      new_array << r.zip_code
      new_array << r.state 
      new_array << r.zone_to_s
      new_array << r.zone_desc 
      new_array << r.address 
      new_array << r.civil_status_to_s
      new_array << r.rg  
      new_array << r.cpf 
      new_array << r.voter_id  
      new_array << r.professional_id 
      new_array << r.professional_serie  
      new_array << r.birth_or_marriage_certificate_id  
      new_array << r.social_id 
      new_array << r.sons_number 
      new_array << r.first_son_age 
      new_array << r.second_son_age  
      new_array << r.third_son_age 
      new_array << r.forth_son_age 
      new_array << r.education_level_to_s
      new_array << r.education_level_desc  
      new_array << r.familiar_income_to_s 
      new_array << r.house_to_s
      new_array << r.house_desc  
      new_array << r.house_type_to_s  
      new_array << r.special_need_to_s
      new_array << r.political_affiliation_to_s
      new_array << r.political_party 
      new_array << r.political_desc  
      new_array << r.religion_to_s
      new_array << r.religion_desc 
      new_array << r.association_to_s
      new_array << r.association_desc  
      new_array << r.cooperative_to_s
      new_array << r.core.try(:name)
      new_array << r.core_identification 
      new_array << r.age_range_to_s
      new_array << r.internet_access_local_to_s
      new_array << r.internet_access_local_desc  
      new_array << r.email 
      new_array << r.house_type_desc 
      new_array << r.special_need_desc 
      new_array << r.special_need_type_to_s
      new_array << r.participation_reason  
      new_array << r.travel_disponibility_to_s
      new_array << r.last_books  
      new_array << r.tv_programs 
      new_array << r.experience  
      new_array << r.other_job 
      new_array << r.agree_with_any_period 
      new_array << r.what_teach  
      new_array << r.subjects  
      new_array << r.has_pc_to_s
      new_array << r.where_use_pc_to_s
      new_array << r.about_pc_use_to_s  
      new_array << r.pc_uses.collect(&:description).join(', ')
      new_array << r.where_use_pc_desc 
      new_array << r.has_internet_to_s
      new_array << r.where_has_internet_to_s  
      new_array << r.where_has_internet_desc 
      new_array << r.internet_uses.collect(&:description).join(', ')
      new_array << r.for_what_use_internet_desc  
      new_array << r.use_social_net_works.collect(&:description).join(', ')
      new_array << r.know_social_net_works.collect(&:description).join(', ')
      new_array << r.know_social_network_desc  
      new_array << r.use_social_network_desc 
      new_array << r.observation 
      new_array << r.identification_on.try(:strftime, "%d/%m/%Y")
      new_array << r.profession
      array << new_array
    end
    array
  end
private

  def get_attribute_value(attribute, array)
    array.each do |a|
      return a.first if a.last == attribute
    end
    ''
  end
  
end

app/controllers/educators_controller.rb
# -*- encoding : utf-8 -*-
class EducatorsController < ApplicationController

  before_filter :load_data, :only => [:edit, :new, :update, :create]
  # GET /educators
  # GET /educators.xml

  def update_rooms
    if params[:educator_id].to_i == 0
      @educator = Educator.new
    else
      @educator = Educator.find(params[:educator_id])
    end
    core = Core.find(params[:core_id])
    @rooms = core.rooms

    respond_to do |format|
      format.js if request.xhr?
    end
  end

  def index
    @educators = Educator.all(:conditions => "core_id IN (SELECT id FROM cores WHERE city_id IN (#{@cities_ids}))", :include => [:core, :rooms], :order => "name ASC")

    respond_to do |format|
      format.csv do
        @educators = Educator.to_csv_file(@educators)
        @filename = 'monitores.csv'
        @output_encoding = 'UTF-8'
      end
      format.html # index.html.erb
      format.xml  { render :xml => @educators }
      
    end
  end

  # GET /educators/1
  # GET /educators/1.xml
  def show
    @educator = Educator.first(:conditions => "id = #{params[:id]}")
    if @educator.nil?
      redirect_to educators_path 
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @educator }
      end
    end
  end

  # GET /educators/new
  # GET /educators/new.xml
  def new
    @educator = Educator.new
    @rooms = []
    1.times {@educator.phones.build}
    @educator.social_participations.build
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @educator }
    end
  end

  # GET /educators/1/edit
  def edit
    @educator = Educator.find(params[:id], :include => [:social_participations, :phones, 
      :educators_education_exps, :educators_education_exps])

    if @educator.core.nil?
      @rooms = []
    else
      @rooms = @educator.core.rooms
    end

    @union_movement_desc = @educator.social_participations.first.union_movement_desc if !@educator.social_participations.first.nil?
    @ong_desc = @educator.social_participations.first.ong_desc if !@educator.social_participations.first.nil?
    @years = @educator.educators_education_exps.first.years if !@educator.educators_education_exps.first.nil?
    @popular_education_years = @educator.educators_education_exps.first.popular_education_years if !@educator.educators_education_exps.first.nil?
  end

  # POST /educators
  # POST /educators.xml
  def create
    @educator = Educator.new(params[:educator])
    ong_desc = params[:ong_desc]
    union_movement_desc = params[:union_movement_desc]
    educator_years = params[:educator_years]
    educator_popular_education_years = params[:educator_popular_education_years]
    respond_to do |format|
      if @educator.save
        if !@educator.social_participations.first.nil?
          @educator.social_participations.first.save_with_descs(ong_desc, union_movement_desc)
        end
        if !@educator.educators_education_exps.first.nil?
          @educator.educators_education_exps.first.update_with_years(educator_years, educator_popular_education_years)
        end
        flash[:success] = t('educator.created')
        format.html { redirect_to(educators_path) }
        format.xml  { render :xml => @educator, :status => :created, :location => @educator }
      else
        if @educator.core_id.nil?
          @rooms = []
        else
          @rooms = Core.find(core_id).rooms
        end
        
        flash[:error] = t('default_error_message')
        format.html { render :action => "new" }
        format.xml  { render :xml => @educator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /educators/1
  # PUT /educators/1.xml
  def update
    @educator = Educator.find(params[:id])
    ong_desc = params[:ong_desc]
    union_movement_desc = params[:union_movement_desc]
    educator_years = params[:educator_years]
    educator_popular_education_years = params[:educator_popular_education_years]
    respond_to do |format|
      if @educator.update_attributes(params[:educator])
        if !@educator.social_participations.first.nil?
          @educator.social_participations.first.save_with_descs(ong_desc, union_movement_desc)
        end
        if !@educator.educators_education_exps.first.nil?
          @educator.educators_education_exps.first.update_with_years(educator_years, educator_popular_education_years)
        end
        flash[:success] = t('educator.updated')
        format.html { redirect_to(educators_path) }
        format.xml  { head :ok }
      else
        if @educator.core_id.nil?
          @rooms = []
        else
          @rooms = Core.find(core_id).rooms
        end
        flash[:error] = t('default_error_message')
        format.html { render :action => "edit" }
        format.xml  { render :xml => @educator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /educators/1
  # DELETE /educators/1.xml
  def destroy
    @educator = Educator.find(params[:id])
    @educator.destroy

    respond_to do |format|
      format.html { redirect_to(educator_url) }
      format.xml  { head :ok }
    end
  end

  def load_data
    @cores = Core.all(:conditions => "city_id IN (#{@cities_ids})").collect {|c| ["#{c.community}", c.id]}
    @genders = Coordinator::GENDERS
    @ethnicities = Coordinator::ETHNICITIES
    @zones = Coordinator::ZONES
    @civil_status = Coordinator::CIVIL_STATUS
    @sons_number = Coordinator::SONS_NUMBER
    @education_levels = Coordinator::EDUCATION_LEVELS
    @familiar_income = Coordinator::FAMILIAR_INCOME
    @houses = Coordinator::HOUSES
    @house_types = Coordinator::HOUSE_TYPES
    @political_affiliations = Coordinator::POLITICAL_AFFILIATIONS
    @political_parties = Coordinator::POLITICAL_PARTIES
    @religions = Coordinator::RELIGIONS
    @associations = Coordinator::ASSOCIATIONS
    @cooperatives = Coordinator::COOPERATIVES
    @professional_exps = ProfessionalExp.all
    @education_exps = EducationExp.all
    @use_social_networks = UseSocialNetWork.all
    @know_social_networks = KnowSocialNetWork.all
    @internet_uses = InternetUse.all
    @pc_uses = PcUse.all
  end
end

app/views/educators/_education_exp_fields.html.haml
- @education_exps.each do |e|
  = check_box_tag 'educator[education_exp_ids][]', e.id, @educator.education_exps.include?(e)
  = e.education_type
%br/
- 5.times do |i|
  = radio_button_tag 'educator_years', i, @years == i
  = get_label_with_years(i)
%br/
= t('education_exp.popular_education_years')
%br/
- 5.times do |i|
  = radio_button_tag 'educator_popular_education_years', i, @popular_education_years == i
  = get_label_with_years(i)

app/views/educators/_professional_exp_fields.html.haml
- @professional_exps.each do |p|
  = check_box_tag 'educator[professional_exp_ids][]', p.id, @educator.professional_exps.include?(p)
  = p.area

app/views/educators/_rooms.html.haml
- rooms.each do |r|
  = check_box_tag 'educator[room_ids][]', r.id, educator.rooms.include?(r)
  = r.name

app/views/educators/_show.html.haml
:javascript

  $(document).ready(function() {
    zebraListing();
  });

%p{:style => hidden_fields} 
  %b= 'Identificação dos dados realizada em'
  = educator.identification_on.try(:strftime, '%d/%m/%Y')

%p  
  %b= "#{t('coordinator.core')}:"
  = educator.core.try(:name)
%p
  %b= "#{t('coordinator.start_date_to_students')}:"
  = educator.start_date_to_students.try(:strftime, '%d/%m/%Y')

%p{:style => hidden_fields}
  %b= "Identificação do núcleo:"
  = educator.core_identification

%p{:style => hidden_fields}
  %b= "Faixa etária"
  = educator.age_range_to_s

%p
  %b= "#{t('coordinator.age')}:"
  = educator.age
%p
  %b= "#{t('coordinator.gender')}:"
  = educator.gender_to_s
%p
  %b= "#{t('coordinator.dob')}:"
  = educator.dob.try(:strftime, '%d/%m/%Y')
%p
  %b= "#{t('coordinator.ethnicity')}:"
  = educator.ethnicity_to_s
%p
  %b= "#{t('coordinator.hometown')}:"
  = educator.hometown
%p
  %b= "#{t('coordinator.state')}:"
  = educator.state
%p
  %b= "#{t('coordinator.zone')}:"
  = educator.zone_to_s

%p{:style => hidden_fields}
  %b= "Qual"
  = educator.zone_desc

%p
  %b= "#{t('coordinator.address')}:"
  = educator.address

%p{:style => hidden_fields}
  %b= "Comunidade/Bairro"
  = educator.district

%p{:style => hidden_fields}
  %b= "CEP"
  = educator.zip_code

%p
  %b= "#{t('coordinator.civil_status')}:"
  = educator.civil_status_to_s
%p
  %b= "#{t('coordinator.rg')}:"
  = educator.rg
%p
  %b= "#{t('coordinator.cpf')}:"
  = educator.cpf
%p
  %b= "#{t('coordinator.voter_id')}:"
  = educator.voter_id
%p
  %b= "#{t('coordinator.professional_id')}:"
  = educator.professional_id
%p
  %b= "#{t('coordinator.professional_serie')}:"
  = educator.professional_serie
%p
  %b= "#{t('coordinator.birth_or_marriage_certificate_id')}:"
  = educator.birth_or_marriage_certificate_id
%p
  %b= "#{t('coordinator.social_id')}:"
  = educator.social_id
%p
  %b= "#{t('coordinator.sons_number.title')}:"
  = educator.sons_number
%p
  - sons_age = [["primeiro", educator.first_son_age], ["segundo", educator.second_son_age], ["terceiro", educator.third_son_age], ["quarto", educator.forth_son_age]]
  - sons_age.each do |s|
    - if !s.last.blank?
      %b= "Idade do #{s.first} filho:"
      = s.last
      %p
  
  %b= "#{t('coordinator.education_level')}:"
  = educator.education_level_to_s
  - if !educator.education_level_desc.blank?
    = "(#{educator.education_level_desc})"
%p
  %b= "#{t('coordinator.house.title')}:"
  = educator.house_to_s
  - if !educator.house_desc.blank?
    = "(#{educator.house_desc})"
%p
  %b= "#{t('coordinator.house_type')}:"
  = educator.house_type_to_s

%p
  %b= "(#{educator.familiar_income})"
  = educator.familiar_income_to_s

%p{:style => hidden_fields}
  %b= t('which')
  = educator.house_type_desc

%p
  %b= "#{t('coordinator.special_need')}:"
  = educator.special_need_to_s

%p{:style => hidden_fields}
  %b= "Especifique"
  = educator.special_need_desc

%p{:style => hidden_fields}
  %b= "Por que interessou-se pelo programa de alfabetização?"
  = educator.participation_reason

%p{:style => hidden_fields}
  %b= "Disponibilidade viagem?"
  = educator.travel_disponibility_to_s

%p{:style => hidden_fields}
  %b= " 3 últimos livros lidos:"
  = educator.last_books

%p{:style => hidden_fields}
  %b= "Cite 3 programas de televisão por ordem de interesse que assiste diariamente"
  = educator.tv_programs

%p{:style => hidden_fields}
  %b= "Você tem experiência em alfabetização de jovens e adultos? Conte-nos sobre."
  = educator.experience

%p{:style => hidden_fields}
  %b= "Você tem compromisso com outro trabalho? Quais os dias da semana e horário?"
  = educator.other_job

%p{:style => hidden_fields}
  %b= "A educação de jovens e adultos pode acontecer em qualquer horário. Você concorda com essa afirmação? Por que?"
  = educator.agree_with_any_period
  
%p{:style => hidden_fields}
  %b= "O que se deve ensinar numa sala para jovens e adultos?"
  = educator.what_teach
  
%p{:style => hidden_fields}
  %b= "Liste possíveis temas/conteúdos que gostaria de estudar e que ajudariam você a exercer seu papel de alfabetizador(a)"
  = educator.subjects
  
%p{:style => hidden_fields}
  %b= "Tem computador?"
  = educator.has_pc_to_s
  
%p{:style => hidden_fields}
  %b= "Se não, onde acessa:"
  = educator.where_use_pc_to_s
  
%p{:style => hidden_fields}
  %b=  "Quais"
  = educator.where_use_pc_desc
  
%p{:style => hidden_fields}
  %b= "Tem internet"
  = educator.has_internet_to_s

- if educator.has_internet == true
  %p{:style => hidden_fields}
    %b= "Onde"
    = educator.where_has_internet_to_s
  
  - if educator.where_has_internet == 3 
    %p{:style => hidden_fields}
      %b= "Quais"
      = educator.where_has_internet_desc


%p{:style => hidden_fields}
  %b= "Sobre o uso do computador, você:"
  = educator.about_pc_use_to_s

%p{:style => hidden_fields}
  %b= "Quais usos que você faz do computador"
  = educator.pc_uses.map(&:description).join(", ")

%p{:style => hidden_fields}
  %b= "O uso que faz da Internet visa ao"
  = educator.internet_uses.map(&:description).join(", ")

- if educator.internet_uses.include?(4)
  %p{:style => hidden_fields}
    %b= "Quais"
    = educator.for_what_use_internet_desc

%p{:style => hidden_fields}
  %b= "Conhece redes sociais?"
  = educator.know_social_network_to_s

%p{:style => hidden_fields}
  %b= "Quais"
  = educator.know_social_net_works.map(&:description).join(", ")

- if educator.know_social_net_works.include?(4)
  %p{:style => hidden_fields}
    %b= "Outras redes sociais que conhece"
    = educator.know_social_network_desc

%p{:style => hidden_fields}
  %b= "Quais redes sociais usa"
  = educator.which_social_network

%p{:style => hidden_fields}
  %b= "Quais"
  = educator.use_social_net_works.map(&:description).join(", ")

- if educator.use_social_net_works.include?(4)
  %p{:style => hidden_fields}
    %b= "Outras redes sociais que usa"
    = educator.use_social_network_desc

%p{:style => hidden_fields}
  %b= "Espaço para observações gerais"
  = educator.observation

%p
  %b= "#{t('coordinator.political_affiliation.title')}:"
  = educator.political_affiliation_to_s
%p
  %b= "Partido:"
  = educator.political_party_to_s
  - if !educator.political_desc.blank?
    = educator.political_desc
  
%p
  %b= "#{t('coordinator.religion.title')}:"
  = educator.religion_to_s
  - if !educator.religion_desc.blank?
    = "(#{educator.religion_desc})"
%p
  %b= "#{t('coordinator.association.title')}:"
  = educator.association_to_s
  - if !educator.association_desc.blank?
    = educator.association_desc
%p
  %b= "#{t('coordinator.cooperative.title')}:"
  = educator.cooperative_to_s
%p
  %b= "Turmas em que participa:"
  %ul
    - educator.rooms.each do |r|
      - if r.core.try(:name).blank?
        %li= "#{r.name}"
      - else
        %li= "#{r.name} - #{r.core.try(:name)}"
%p
  %b= "Telefones:"
  %ul
    - educator.phones.each do |p|
      %li= "(#{p.dd}) #{p.number} <i>#{p.phone_type_to_s}</i>".html_safe


%p{:style => hidden_fields}
  %b= "Local de acceso a internet"
  = educator.internet_access_local_to_s
- if !educator.internet_access_local.nil?
  - if educator.internet_access_local.include?(3)
    %p{:style => hidden_fields}
      %b= "Quais"
      = educator.internet_access_local_desc

%p{:style => hidden_fields}
  %b= "E-mail"
  = educator.email

app/views/educators/edit.html.haml
%h1.title= t('educator.edit')
.action_back 
  = link_to t('back'), educators_path, :class => 'back_link'
= render 'form', :button => t('update')

app/views/educators/index.html.haml
:javascript
  $(document).ready(function(){
    $('a.more').click(function(){
      $(this).parent().parent().next().children().children().slideToggle();
      return false;
    })
  });


%h1.title= t('educator.listing')
.actions 
  = render '/layouts/shared/add_button', :new_label=>t('educator.new'), :new_path => new_educator_path, :permission => :educators
  - if current_user.admin?
    .presence_lists= link_to 'Exportar', educators_path(:format => :csv)
= render '/layouts/shared/filter_bar'

%table{:class => 'list'}
  %thead
    %tr
      %th= t('educator.name')
      %th{:style => 'width: 20px;'}
      %th{:style => 'width: 20px;'}
  %tbody
    - @educators.each do |educator|
      %tr{:class => 'more-click'}
        %td{:class => 'first-td'}= raw"<a href='#' class='more'></a>"+educator.name
        = render '/layouts/shared/edit_delete', :edit_path => edit_educator_path(educator), :delete_obj => educator, :permission => :educators
      %tr{:class => 'more-info'}
        %td{:colspan => 3}
          %div
            = render 'show', :educator => educator
%br

app/views/educators/new.html.haml
%h1.title= t('educator.new_title')
.action_back 
  = link_to t('back'), educators_path, :class => 'back_link'
= render 'form', :button => t('create')

app/views/educators/show.html.haml
%div{:style => 'margin-top: -13px;'}
  %h1.title= @educator.name
  .action_back 
    = link_to t('back'), :back, :class => 'back_link'
= render 'show', :educator => @educator

app/views/educators/update_rooms.js.haml
$("#rooms_field_div").html("#{escape_javascript(render 'rooms', :rooms => @rooms, :educator => @educator).html_safe}")