config/routes.rb
# -*- encoding : utf-8 -*-
Alfa::Application.routes.draw do

  resources :occupations

  resources :world_readings

  resources :students do
    resources :presence_list_comments
  end

  resources :rooms do
    resources :lecture_days
  end

  root :to => "cores#index"
  resources :cores
  resources :coordinators
  resources :educators
  resources :users
  resources :user_sessions
  match 'sign_up' => 'users#sign_up', :as => 'sign_up'
  match 'sign_in' => 'user_sessions#new', :as => 'sign_in'
  match 'sign_out' => 'user_sessions#destroy', :as => 'sign_out'
  match 'update_city' => 'cores#update_city', :as => 'update_city'
  match 'update_rooms/:educator_id/:core_id' => 'educators#update_rooms', :as => 'update_rooms'
  match 'student_update_rooms/:student_id/:core_id' => 'students#update_rooms', :as => 'student_update_rooms'
  match 'coordinator_update_rooms/:coordinator_id/:core_id' => 'coordinators#update_rooms', :as => 'coordinator_update_rooms'
  match 'students_without_mother_name' => 'students#without_mother_name', :as => 'without_mother_name'
  match 'update_cancelled/:id' => 'lecture_days#update_cancelled', :as => 'update_cancelled'
  match 'new_lecture_day/:room_id' => 'lecture_days#new_lecture_day', :as => 'new_lecture_day'
  match ':room_id/:month/fix_presence_list' => 'presences_list#fix', :as => 'fix_presence_list'
  match ':room_id/:month/finish_presence_list' => 'presences_list#finish', :as => 'finish_presence_list'
  match ':room_id/:month/reopen_presence_list' => 'presences_list#reopen', :as => 'reopen_presence_list'
  match ':room_id/presences_list' => 'presences_list#index', :as => 'presences_list'
  match ':room_id/:month/presences_list' => 'presences_list#edit', :as => 'edit_presences_list'
  match 'update_presence/:id/:status' => 'presences_list#update', :as => 'update_presence'
  match 'update_student_presences/:room_id/:month/:student_id/:status' => 'presences_list#update_student_presences', :as => 'update_student_presences'
  match 'reports' => 'reports#index', :as => 'reports'
  match 'show_report' => 'reports#show', :as => 'show_report'
  match 'report_update_rooms/:core_id' => 'reports#update_rooms', :as => 'report_update_rooms'
  match 'show_full_report' => 'reports#show_full_report', :as => 'show_full_report'

  match 'show_second_report/:column/:second_column/:core_id/:room_id' => 'reports#show_second_report', :as => 'show_second_report'
  match 'students/:student_id/:month/show_presence_list_comments' => 'presence_list_comments#show', :as => 'show_presence_list_comments'
  
end

app/models/lecture_day.rb
class LectureDay < ActiveRecord::Base
  belongs_to :room
  has_many :presences, :dependent => :destroy

  after_save :create_presences, :update_presences_status
  before_destroy :verify_if_presence_list_is_closed
  before_save :verify_if_presence_list_is_closed
  validates_presence_of :month

  def lecture_on_to_date
    if !self.lecture_on.nil?
      Time.at(self.lecture_on)
    else
      nil
    end
  end

  def self.create_lectures(start_on, end_on, room_id, lecture_days)
    return false, "Por favor, preencha todos os campos obrigatórios corretamente" if invalid_date(start_on) || invalid_date(end_on) || room_id.blank? || not_lectures_days(lecture_days)
    return false, "A data de término deve ser maior que a da de início das aulas" if end_on_before_or_equals_start_on?(start_on, end_on)
    start_on = Date.strptime(start_on, '%d/%m/%Y')
    end_on = Date.strptime(end_on, '%d/%m/%Y')
    days_of_week = []
    lecture_days.each do |d|
      if !d["week_day"].blank?
        days_of_week << {:week_day => d["week_day"].to_i, :start_at => d["start_at"], :end_at => d["end_at"]} 
      end
    end
    days_of_week.each do |d|
      create_lectures_for_day_of_week(d[:week_day], start_on, end_on, room_id, d[:start_at], d[:end_at])
    end
    return true, ''
  end

  def period
    if self.start_at.blank? || self.end_at.blank?
      return ''
    else
      "#{self.start_at.try(:strftime, '%H:%M')} às #{self.end_at.try(:strftime, '%H:%M')}"
    end
  end

private

  def verify_if_presence_list_is_closed
    presence_list = PresenceList.first(:conditions => "month = #{self.month} AND room_id = #{self.room_id}")
    if !presence_list.blank?
      errors.add(:base, "Não é possível apagar o dia de aula, pois a lista de presença foi fechada")
    end
    errors.blank?
  end

  def create_presences
    self.room.students.each do |s|
      p = Presence.first(:conditions => "lecture_day_id = #{self.id} AND student_id = #{s.id}")
      if p.nil?
        Presence.create(:lecture_day_id => self.id, :student_id => s.id, :room_id => self.room_id, :month => self.month)
      else
        p.update_attributes(:month => self.month)
      end
    end
  end

  def update_presences_status
    if self.cancelled_changed?
      if self.cancelled
         ActiveRecord::Base.connection.execute "UPDATE presences SET has_class = #{Presence::NO_CLASS} WHERE lecture_day_id = #{self.id}"
      else
        ActiveRecord::Base.connection.execute "UPDATE presences SET has_class = #{Presence::WITH_CLASS} WHERE lecture_day_id = #{self.id}"
      end
    end
  end

  def self.create_lectures_for_day_of_week(day_of_week, start_on, end_on, room_id, start_at, end_at)
    lecture_days = []
    date = start_on
    if date.wday == day_of_week
      while (date <= end_on)
        lecture_days << date
        date += 7.days
      end
    else
      while ((date).wday != day_of_week)
        date = date.next
      end
      while (date <= end_on)
        lecture_days << date
        date += 7.days
      end
    end
    lecture_days.each do |l|
      create(:lecture_on => l.to_time.to_i, :week_day => day_of_week, :day => l.day, :month => l.month, :year => l.year, :room_id => room_id, :start_at => start_at, :end_at => end_at)
    end
  end

  def self.not_lectures_days(lecture_days)
    has_days = true
    lecture_days.each do |d|
      has_days = false if !d["week_day"].blank?
    end
    has_days
  end

  def self.invalid_date(date)
    begin
      Date.strptime(date, '%d/%m/%Y')
    rescue
      return true
    end
    false
  end

  def self.end_on_before_or_equals_start_on?(first_date, second_date)
    Date.strptime(second_date, '%d/%m/%Y') <= Date.strptime(first_date, '%d/%m/%Y')
  end

end

app/controllers/lecture_days_controller.rb
class LectureDaysController < ApplicationController
  
  before_filter :load_form_data, :only => [:new, :create, :edit, :update, :new_lecture_day]


  def update_cancelled
    @lecture_day = LectureDay.find(params[:id])
    if @lecture_day.cancelled
      @lecture_day.cancelled = false
    else
      @lecture_day.cancelled = true
    end
    @lecture_day.save
  end

  def index
    @room = Room.find(params[:room_id])
    @lecture_days = LectureDay.all(:conditions => "room_id = #{@room.id}", :order => "lecture_on ASC")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lecture_days }
    end
  end

  def show
    @lecture_day = LectureDay.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lecture_day }
    end
  end

  # GET /lecture_days/new
  # GET /lecture_days/new.xml
  def new
    @lecture_day = LectureDay.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lecture_day }
    end
  end

  def new_lecture_day
    @lecture_day = LectureDay.create(:room_id => params[:room_id], :month => 0)
  end

  # GET /lecture_days/1/edit
  def edit
    @lecture_day = LectureDay.find(params[:id])
  end

  # POST /lecture_days
  # POST /lecture_days.xml
  def create
    @lecture_day = LectureDay.new
    respond_to do |format|
      result, error_message = LectureDay.create_lectures(params[:start_on], params[:end_on], params[:room_id], params[:lecture_days])
      if result
        flash[:success] = 'Cadastro de aulas realizado com sucesso'
        format.html { redirect_to(room_lecture_days_path(:room_id => params[:room_id])) }
        format.xml  { render :xml => @lecture_day, :status => :created, :location => @lecture_day }
      else
        flash[:error] = error_message
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /lecture_days/1
  # PUT /lecture_days/1.xml
  def update
    @lecture_day = LectureDay.find(params[:id])
    params[:lecture_day][:lecture_on] = Date.strptime(params[:lecture_day][:lecture_on], '%d/%m/%Y').to_time.to_i
    respond_to do |format|
      if @lecture_day.update_attributes(params[:lecture_day])
        flash[:success] = 'Cadastro de aula atualizado com sucesso'
        format.html { redirect_to(room_lecture_days_path(:room_id => params[:room_id])) }
        format.xml  { head :ok }
      else
        flash[:error] = @lecture_day.errors.full_messages.join(", ")
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lecture_day.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lecture_days/1
  # DELETE /lecture_days/1.xml
  def destroy
    @lecture_day = LectureDay.find(params[:id])
    @lecture_day.destroy

    respond_to do |format|
      if @lecture_day.errors.blank?
        flash[:success] = 'Dia de aula apagado com sucesso'
      else
        flash[:error] = @lecture_day.errors.full_messages.first
      end
      format.html { redirect_to(room_lecture_days_path(:room_id => params[:room_id])) }
      format.xml  { head :ok }
    end
  end

protected

  def load_form_data
    @room = Room.find(params[:room_id])
  end

end

app/helpers/lecture_days_helper.rb
module LectureDaysHelper

  def generate_cancelled_button(cancelled, id)
    if cancelled
      string = "Descancelar"
      klass = "uncancel"
    else
      string = "Cancelar"
      klass = "cancel"
    end
    "#{link_to string, update_cancelled_path(:id => id), :class => klass, :remote => true}"
  end

end

app/views/lecture_days/_form.html.haml
= form_for [@room, @lecture_day], :html => {:id => 'formframe'} do |f|
  %div
    = label_tag 'Início das aulas*'
    = text_field_tag :start_on
  %div
    = label_tag 'Término das aulas*'
    = text_field_tag :end_on
  :javascript
    $(document).ready(function() {
      $("#start_on").mask("99/99/9999");
      $("#end_on").mask("99/99/9999");
    });
  %div
    = fields_for "lecture_days[]", @lecture_day do |f|
      - 5.times do |i|
        = render 'lecture_day', :f => f, :i => i
    %div
      .form_actions
        .add
          = link_to 'Adicionar novo dia', '#', :id => 'add_lecture_day'
        :javascript
          $(document).ready(function() {
              $("#add_lecture_day").click(function() {
                var days = [0, 1, 2, 3, 4];
                stop_loop = false;
                  days.forEach(function(item){ 
                    if (($("#lecture_day_" + item).css('display') == 'none') && !stop_loop){
                      jQuery("#lecture_day_" + item).attr('style','display:block; !important');
                      stop_loop = true;
                    }
                  });
                  return false;
              });
          });

  .actions
    = f.submit "Criar"

app/views/lecture_days/_lecture_day.html.haml
- if i == 0
  - style = ""
- else
  - style = "display: none;"

%div{:id => "lecture_day_#{i}", :style => "#{style}", :class => 'lecture_day'}  
  = label_tag 'Dia da semana*', nil, :class => "week_day"
  = f.select :week_day, options_for_select(Period::DAYS_OF_WEEK), {:include_blank => 'Selecione'}, {:id => "week_day_#{i}"}
  = label_tag 'Horário de início'
  = f.text_field :start_at, :id => "start_at_#{i}", :class => "start_at"
  = label_tag 'Horário de término'
  = f.text_field :end_at, :id => "end_at_#{i}", :class => "end_at"
  :javascript
    $(document).ready(function() {
      $(".start_at").mask("99:99");
      $(".end_at").mask("99:99");
    });

app/views/lecture_days/edit.html.haml
%h1.title= "Alterar dia de aula da turma #{@room.name}"
.action_back 
  = link_to t('back'), room_lecture_days_path(:room_id => params[:room_id]), :class => 'back_link'
= form_for [@room, @lecture_day], :html => {:id => 'formframe'} do |f|
  %div
    = f.label :lecture_on
    %br
    = f.text_field :lecture_on, :value => @lecture_day.lecture_on_to_date.try(:strftime, '%d/%m/%Y')
  %div
    = f.label :start_at
    %br
    = f.text_field :start_at
  %div
    = f.label :end_at
    %br
    = f.text_field :end_at
  %div
    = f.label :cancelled
    = f.check_box :cancelled
  .actions
    = f.submit "Alterar"

  :javascript
    $(document).ready(function() {
      $("#lecture_day_lecture_on").mask("99/99/9999");
      $("#lecture_day_start_at").mask("99:99");
      $("#lecture_day_end_at").mask("99:99");
    });

app/views/lecture_days/index.html.haml
%h1.title
  = "Dias de aula"
.actions 
  = link_to t('back'), presences_list_path(:room_id => params[:room_id]), :class => 'back_link'
  = render '/layouts/shared/add_button', :new_label=> "Cadastrar aulas", :new_path => new_room_lecture_day_path(:room_id => params[:room_id]), :permission => :lecture_days
  = render '/layouts/shared/add_button', :new_label=> "Cadastrar aula", :new_path => new_lecture_day_path(:room_id => params[:room_id]), :permission => :lecture_days, :style => "border-right: none;"
= render '/layouts/shared/filter_bar'
%table{:class => 'list'}
  %thead
    %tr
      %th= "Dia"
      %th= "Horário"
      %th{:style => 'width: 20px;'}
      %th{:style => 'width: 20px;'}
      %th{:style => 'width: 20px;'}
  %tbody
    - @lecture_days.each do |lecture_day|
      %tr{:class => 'more-click'}
        %td{:class => 'first-td'}= lecture_day.lecture_on_to_date.try(:strftime, '%d/%m/%Y')
        %td= lecture_day.period
        %td
          - if can? :update, lecture_day
            %div{:id => "cancelled_button_#{lecture_day.id}"}
              = generate_cancelled_button(lecture_day.cancelled, lecture_day.id).html_safe
        = render '/layouts/shared/edit_delete', :edit_path => edit_room_lecture_day_path(:room_id => params[:room_id], :id => lecture_day.id), :delete_obj => room_lecture_day_path(:id => lecture_day.id), :permission => :lecture_days
        

app/views/lecture_days/new.html.haml
%h1.title= "Cadastro de aulas da #{@room.name}"
.action_back 
  = link_to t('back'), room_lecture_days_path(:room_id => params[:room_id]), :class => 'back_link'
= render 'form'

app/views/lecture_days/new_lecture_day.html.haml
%h1.title= "Cadastro de dia de aula da #{@room.name}"
.action_back 
  = link_to t('back'), room_lecture_days_path(:room_id => params[:room_id]), :class => 'back_link'
= form_for [@room, @lecture_day], :html => {:id => 'formframe'} do |f|
  %div
    = f.label :lecture_on
    %br
    = f.text_field :lecture_on, :value => @lecture_day.lecture_on_to_date.try(:strftime, '%d/%m/%Y')
  %div
    = f.label :start_at
    %br
    = f.text_field :start_at
  %div
    = f.label :end_at
    %br
    = f.text_field :end_at
  %div
    = f.label :cancelled
    = f.check_box :cancelled
  .actions
    = f.submit "Cadastrar"

  :javascript
    $(document).ready(function() {
      $("#lecture_day_lecture_on").mask("99/99/9999");
      $("#lecture_day_start_at").mask("99:99");
      $("#lecture_day_end_at").mask("99:99");
    });

app/views/lecture_days/show.html.haml
%p#notice= notice

%p
  %b Lecture on:
  = @lecture_day.lecture_on
%p
  %b Week day:
  = @lecture_day.week_day
%p
  %b Day:
  = @lecture_day.day
%p
  %b Month:
  = @lecture_day.month
%p
  %b Year:
  = @lecture_day.year
%p
  %b Start at:
  = @lecture_day.start_at
%p
  %b End at:
  = @lecture_day.end_at
%p
  %b Room:
  = @lecture_day.room

= link_to 'Edit', edit_lecture_day_path(@lecture_day)
\|
= link_to 'Back', lecture_days_path

app/views/lecture_days/update_cancelled.js.haml
$("#cancelled_button_#{@lecture_day.id}").html("#{escape_javascript(generate_cancelled_button(@lecture_day.cancelled, @lecture_day.id).html_safe)}")